---
  # Common kafka broker environment variables
  x-kafka-broker-env: &kafka-broker-env
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    KAFKA_JMX_HOSTNAME: localhost
    KAFKA_ENABLE_KRAFT: yes
    KAFKA_PROCESS_ROLES: 'broker,controller'
    KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093,2@broker-2:29093'
    # KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@broker:29093,2@broker-2:29093'
    # KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
    KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
    KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    # https://docs.confluent.io/platform/current/monitor/cp-logging.html
    KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    KAFKA_METADATA_LOG_DIR: /tmp/kraft-metadata-logs
    # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
    # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
    # CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    # KAFKA_CLUSTER_ID: "$(bin/kafka-storage.sh random-uuid)" 
    CLUSTER_ID: 'MTkwSDkzMDg5KTdFNDJCRU'
    KAFKA_CLUSTER_ID: 'MTkwSDkzMDg5KTdFNDJCRU'
    KAFKA_KRAFT_CLUSTER_ID: 'MTkwSDkzMDg5KTdFNDJCRU'

  # Common kafka broker configuration
  x-kafka-broker-common: &kafka-broker-common
    image: bitnami/kafka:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dwh_network

  # Common kafka connect environment variables
  x-kafka-connect-env: &kafka-connect-env
    CONNECT_BOOTSTRAP_SERVERS: 'broker:29092,broker-2:29092'
    # CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
    CONNECT_GROUP_ID: compose-connect-group
    CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
    CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 2
    CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
    CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 2
    CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
    CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 2
    CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
    CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
    CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    # CLASSPATH required due to CC-2422
    CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.6.1.jar
    # CONNECT_PRODUCER_MAX_REQUEST_SIZE: 20971520
    # CONNECT_PRODUCER_BATCH_SIZE: 32768  # Reduce batch size (default is 16384)
    CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
    CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
    CONNECT_ERRORS_RETRY_TIMEOUT: 90000
    CONNECT_ERRORS_RETRY_DELAY_MAX_MS: 120000
    ###CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/tmp/ext-plugins"
    CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars
    ###CONNECT_LOG4J_LOGGERS: "log4j.logger.io.confluent.<connector-name>=DEBUG,org.apache.kafka.connect=DEBUG"
    CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
    CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
    DATABASE_HOSTNAME_SOURCE: $DATABASE_HOSTNAME_SOURCE
    DATABASE_PORT: $DATABASE_PORT
    DATABASE_USER_SOURCE: $DATABASE_USER_SOURCE
    DATABASE_PASSWORD_SOURCE: $DATABASE_PASSWORD_SOURCE
    DATABASE_DB_NAME_SOURCE: $DATABASE_DB_NAME_SOURCE
    # KAFKA_HEAP_OPTS: "-Xms2G -Xmx4G"
    
  # Common kafka connect configuration
  x-kafka-connect-common: &kafka-connect-common
    image: confluentinc/cp-kafka-connect:7.6.3
    depends_on:
          - broker-1
          - broker-2
          - schema-registry
          - postgres
          - dwh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "4g"
        reservations:
          cpus: '0.5'
          memory: "4g"
    volumes:
      # - ./connect-file.properties:/tmp/connect-file.properties
      # - $PWD/connectors:/tmp/data
      # - $PWD/jmx-exporter:/tmp/jmx
      # - $PWD/plugins:/tmp/ext-plugins
      # - $PWD/misc:/tmp/misc
      # - $PWD/config:/tmp/config
      # - $PWD/data:/data
      - $PWD/Connectors Config:/Connectors-Config
      - $PWD/init/init_kafka_connect.sh:/docker-entrypoint-initdb.d/init_kafka_connect.sh
    env_file:
      - $PWD/.env
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init_kafka_connect.sh"]
    networks:
      - dwh_network

  services:
    broker-1:
      <<: *kafka-broker-common
      hostname: broker
      container_name: broker-1
      ports:
        - "9092:9092"
        - "9101:9101"
      environment:
        <<: *kafka-broker-env
        KAFKA_NODE_ID: 1
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:29092,PLAINTEXT_HOST://localhost:9092'
        KAFKA_JMX_PORT: 9101
        KAFKA_LISTENERS: 'PLAINTEXT://broker-1:29092,CONTROLLER://broker-1:29093,PLAINTEXT_HOST://0.0.0.0:9092'
    
    broker-2:
      <<: *kafka-broker-common
      hostname: broker-2
      container_name: broker-2
      ports:
        - "9093:9092"
        - "9102:9101"
      environment:
        <<: *kafka-broker-env
        KAFKA_NODE_ID: 2
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:29092,PLAINTEXT_HOST://localhost:9093'
        KAFKA_JMX_PORT: 9102
        KAFKA_LISTENERS: 'PLAINTEXT://broker-2:29092,CONTROLLER://broker-2:29093,PLAINTEXT_HOST://0.0.0.0:9093'
  
    schema-registry:
      image: confluentinc/cp-schema-registry:7.6.1
      hostname: schema-registry
      container_name: schema-registry
      depends_on:
        - broker-1
        - broker-2
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092,broker-2:29092'
        # SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
        SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
        SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
        SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,OPTIONS'
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: "2g"
          reservations:
            cpus: '0.5'
            memory: "2g"
      networks:
        - dwh_network
    
    kafka-connect-1:
      <<: *kafka-connect-common
      hostname: connect-1
      container_name: kafka-connect-1
      ports:
        - "8083:8083"
      environment:
        <<: *kafka-connect-env
        CONNECT_REST_PORT: 8083
        CONNECT_LISTENERS: http://0.0.0.0:8083
        CONNECT_REST_ADVERTISED_HOST_NAME: "connect-1"
    
    kafka-connect-2:
      <<: *kafka-connect-common
      hostname: connect-2
      container_name: kafka-connect-2
      ports:
        - "8084:8084"
      environment:
        <<: *kafka-connect-env
        CONNECT_REST_PORT: 8084
        CONNECT_LISTENERS: http://0.0.0.0:8084
        CONNECT_REST_ADVERTISED_HOST_NAME: "connect-2"
                
    # rest-proxy:
    #   image: confluentinc/cp-kafka-rest:7.6.1
    #   depends_on:
    #     - broker-1
    #     - broker-2
    #     - schema-registry
    #   ports:
    #     - 8082:8082
    #   hostname: rest-proxy
    #   container_name: rest-proxy
    #   environment:
    #     KAFKA_REST_HOST_NAME: rest-proxy
    #     KAFKA_REST_BOOTSTRAP_SERVERS: 'broker-1:29092,broker-2:29092'
    #     KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    #     KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
    #   deploy:
    #     resources:
    #       limits:
    #         cpus: '0.5'
    #         memory: "1g"
    #       reservations:
    #         cpus: '0.5'
    #         memory: "1g"
    #   networks:
    #     - dwh_network
  
    kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      platform: linux/amd64
      ports:
        - 8090:8080
      depends_on:
        - broker-1
        - broker-2
      environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker-1:29092,broker-2:29092'
        # KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker-1:29092'
        # KAFKA_CLUSTERS_0_METRICS_PORT: 11001
        # KAFKA_CLUSTERS_0_METRICS_TYPE: PROMETHEUS
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: "3g"
          reservations:
            cpus: '0.5'
            memory: "3g"
      networks:
        - dwh_network
    
    postgres:
      image: postgres:latest
      container_name: postgres
      ports:
        - "5432:5432"
      volumes:
        - $PWD/Source Database:/Source-Database
        - $PWD/init/restore-backup.sh:/docker-entrypoint-initdb.d/restore-backup.sh
      environment:
        POSTGRES_USER: $DATABASE_USER_SOURCE
        POSTGRES_PASSWORD: $DATABASE_PASSWORD_SOURCE
        POSTGRES_DB: $DATABASE_DB_NAME_SOURCE
        RESTORE_ENV: staging  
      command: [ "postgres", "-c", "wal_level=logical" ]
      networks:
        - dwh_network
    
    dwh:
      image: postgres:latest
      container_name: dwh
      ports:
        - "5431:5432"
      volumes:
        - $PWD/init/init-dwh.sql:/docker-entrypoint-initdb.d/init-dwh.sql
      environment:
        POSTGRES_USER: $DATABASE_USER_DESTINATION
        POSTGRES_PASSWORD: $DATABASE_PASSWORD_DESTINATION
        POSTGRES_DB: $DATABASE_DB_NAME_DESTINATION
      networks:
        - dwh_network

    pgadmin:
      image: dpage/pgadmin4
      restart: on-failure
      container_name: pgadmin
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      ports:
        - "5050:80"
      depends_on:
        - postgres
        - dwh
      networks:
        - dwh_network

    sqlmesh:
      build: .
      container_name: sqlmesh
      ports:
        - "8000:8000"
      depends_on:
        - dwh
      volumes:
        - $PWD/sqlmesh/:/app/sqlmesh
        - $PWD/init/init-sqlmesh.sh:/docker-entrypoint-initdb.d/init-sqlmesh.sh
      working_dir: /app/sqlmesh
      entrypoint: ["/bin/sh", "/docker-entrypoint-initdb.d/init-sqlmesh.sh"]
      networks:
        - dwh_network
    
  networks:
    dwh_network:
      driver: bridge
